//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunnyChen.Gulu.Filters.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SunnyChen.Gulu.Filters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_FileNameFilter {
            get {
                object obj = ResourceManager.GetObject("BMP_FileNameFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_FileSizeFilter {
            get {
                object obj = ResourceManager.GetObject("BMP_FileSizeFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_FileTypeFilter {
            get {
                object obj = ResourceManager.GetObject("BMP_FileTypeFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the Extensions..
        /// </summary>
        internal static string ERROR_EXTENSION_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_EXTENSION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal size must be less or equal than minmal size..
        /// </summary>
        internal static string ERROR_MAX_LARGER_MIN {
            get {
                return ResourceManager.GetString("ERROR_MAX_LARGER_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunny Chen.
        /// </summary>
        internal static string FILTERAUTHOR_FILENAME {
            get {
                return ResourceManager.GetString("FILTERAUTHOR_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunny Chen.
        /// </summary>
        internal static string FILTERAUTHOR_FILESIZE {
            get {
                return ResourceManager.GetString("FILTERAUTHOR_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunny Chen.
        /// </summary>
        internal static string FILTERAUTHOR_FILETYPE {
            get {
                return ResourceManager.GetString("FILTERAUTHOR_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SunnyChen.ORG.
        /// </summary>
        internal static string FILTERCOMPANY_FILENAME {
            get {
                return ResourceManager.GetString("FILTERCOMPANY_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SunnyChen.ORG.
        /// </summary>
        internal static string FILTERCOMPANY_FILESIZE {
            get {
                return ResourceManager.GetString("FILTERCOMPANY_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SunnyChen.ORG.
        /// </summary>
        internal static string FILTERCOMPANY_FILETYPE {
            get {
                return ResourceManager.GetString("FILTERCOMPANY_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2007-2008 SunnyChen.ORG, all rights reserved..
        /// </summary>
        internal static string FILTERCOPYRIGHT_FILENAME {
            get {
                return ResourceManager.GetString("FILTERCOPYRIGHT_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2007-2008 SunnyChen.ORG, all rights reserved..
        /// </summary>
        internal static string FILTERCOPYRIGHT_FILESIZE {
            get {
                return ResourceManager.GetString("FILTERCOPYRIGHT_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2007-2008 SunnyChen.ORG, all rights reserved..
        /// </summary>
        internal static string FILTERCOPYRIGHT_FILETYPE {
            get {
                return ResourceManager.GetString("FILTERCOPYRIGHT_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter for file name. You can specify different condition/specification (like the file name should be started with some text) and provide a readable value for that specification. Regular expression is supported by this filter..
        /// </summary>
        internal static string FILTERDESC_FILENAME {
            get {
                return ResourceManager.GetString("FILTERDESC_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size filter. This filter is used to determine if the file matches or is in range of the size values. Other files doesn&apos;t match the size criterion will be excluded..
        /// </summary>
        internal static string FILTERDESC_FILESIZE {
            get {
                return ResourceManager.GetString("FILTERDESC_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter for file type. The type of a file is evaluated by its extension. Just specify the extension list here and the files beyond these extensions will be excluded..
        /// </summary>
        internal static string FILTERDESC_FILETYPE {
            get {
                return ResourceManager.GetString("FILTERDESC_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Filter.
        /// </summary>
        internal static string FILTERNAME_FILENAME {
            get {
                return ResourceManager.GetString("FILTERNAME_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Filter.
        /// </summary>
        internal static string FILTERNAME_FILESIZE {
            get {
                return ResourceManager.GetString("FILTERNAME_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type Filter.
        /// </summary>
        internal static string FILTERNAME_FILETYPE {
            get {
                return ResourceManager.GetString("FILTERNAME_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Customized).
        /// </summary>
        internal static string TEXT_CUSTOMIZED {
            get {
                return ResourceManager.GetString("TEXT_CUSTOMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        internal static string TEXT_IMAGE_FILE {
            get {
                return ResourceManager.GetString("TEXT_IMAGE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files.
        /// </summary>
        internal static string TEXT_TEXT_FILE {
            get {
                return ResourceManager.GetString("TEXT_TEXT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave sound files.
        /// </summary>
        internal static string TEXT_WAVE_FILE {
            get {
                return ResourceManager.GetString("TEXT_WAVE_FILE", resourceCulture);
            }
        }
    }
}
