//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunnyChen.Gulu.Gulus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SunnyChen.Gulu.Gulus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic File Operations.
        /// </summary>
        internal static string AMG_CATEGORY {
            get {
                return ResourceManager.GetString("AMG_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the attributes of the files..
        /// </summary>
        internal static string AMG_DESCRIPTION {
            get {
                return ResourceManager.GetString("AMG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FONT FACE=&quot;Tahoma&quot; SIZE=&quot;2.5px&quot; COLOR=&quot;Black&quot;&gt;Attribute Modification allows users modify the attributes for a series of files. These attributes include: the standard ReadOnly, Hidden, Archive and System attributes, and the attributes that related to the date (such as creation date, last modification date etc.). Once you have selected the ReadOnly or System attribute, it is unable to set date attributes for files, because you don&apos;t have access to ReadOnly or System files.&lt;BR/&gt;&lt;BR/&gt;Sometimes it will show the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AMG_DOCUMENT {
            get {
                return ResourceManager.GetString("AMG_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Modification.
        /// </summary>
        internal static string AMG_NAME {
            get {
                return ResourceManager.GetString("AMG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunny Chen.
        /// </summary>
        internal static string AUTHOR_NAME {
            get {
                return ResourceManager.GetString("AUTHOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_ATTRIBUTES {
            get {
                object obj = ResourceManager.GetObject("BMP_ATTRIBUTES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_DELETE {
            get {
                object obj = ResourceManager.GetObject("BMP_DELETE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_FILELIST {
            get {
                object obj = ResourceManager.GetObject("BMP_FILELIST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_MOVECOPY {
            get {
                object obj = ResourceManager.GetObject("BMP_MOVECOPY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_RENAME {
            get {
                object obj = ResourceManager.GetObject("BMP_RENAME", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_SEARCH {
            get {
                object obj = ResourceManager.GetObject("BMP_SEARCH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_STATISTICS {
            get {
                object obj = ResourceManager.GetObject("BMP_STATISTICS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SunnyChen.ORG.
        /// </summary>
        internal static string COMPANY_NAME {
            get {
                return ResourceManager.GetString("COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2007-2008 SunnyChen.ORG, all rights reserved..
        /// </summary>
        internal static string COPYRIGHT {
            get {
                return ResourceManager.GetString("COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics and Reports.
        /// </summary>
        internal static string FLG_CATEGORY {
            get {
                return ResourceManager.GetString("FLG_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates and outputs file list according to the settings..
        /// </summary>
        internal static string FLG_DESCRIPTION {
            get {
                return ResourceManager.GetString("FLG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate File List.
        /// </summary>
        internal static string FLG_NAME {
            get {
                return ResourceManager.GetString("FLG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic File Operations.
        /// </summary>
        internal static string FRG_CATEGORY {
            get {
                return ResourceManager.GetString("FRG_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming files according to the settings..
        /// </summary>
        internal static string FRG_DESCRIPTION {
            get {
                return ResourceManager.GetString("FRG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming.
        /// </summary>
        internal static string FRG_NAME {
            get {
                return ResourceManager.GetString("FRG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics and Reports.
        /// </summary>
        internal static string FSG_CATEGORY {
            get {
                return ResourceManager.GetString("FSG_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting files by last access time, last modified time, etc..
        /// </summary>
        internal static string FSG_DESCRIPTION {
            get {
                return ResourceManager.GetString("FSG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Date Statistics.
        /// </summary>
        internal static string FSG_NAME {
            get {
                return ResourceManager.GetString("FSG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic File Operations.
        /// </summary>
        internal static string MCG_CATEGORY {
            get {
                return ResourceManager.GetString("MCG_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves or copies files to a specific folder..
        /// </summary>
        internal static string MCG_DESCRIPTION {
            get {
                return ResourceManager.GetString("MCG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move or Copy.
        /// </summary>
        internal static string MCG_NAME {
            get {
                return ResourceManager.GetString("MCG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic File Operations.
        /// </summary>
        internal static string PDG_CATEGORY {
            get {
                return ResourceManager.GetString("PDG_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected files permanently..
        /// </summary>
        internal static string PDG_DESCRIPTION {
            get {
                return ResourceManager.GetString("PDG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FONT FACE=&quot;Tahoma&quot; SIZE=&quot;2.5px&quot; COLOR=&quot;Black&quot;&gt;The permanent delete gulu is used for deleting files permanently. You cannot recover the files deleted even if you use some third-party disk utilities. Before the action is going to be taken, a dialog box will appear to let user input &quot;OK&quot; so that the deleting operation is absolutely confirmed. This is because that the operation doesn&apos;t require the backup of the original files and you cannot get a rollback of the operation.&lt;/FONT&gt;.
        /// </summary>
        internal static string PDG_DOCUMENT {
            get {
                return ResourceManager.GetString("PDG_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Delete.
        /// </summary>
        internal static string PDG_NAME {
            get {
                return ResourceManager.GetString("PDG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic File Operations.
        /// </summary>
        internal static string SRG_CATEGORY {
            get {
                return ResourceManager.GetString("SRG_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches or replaces texts in the files..
        /// </summary>
        internal static string SRG_DESCRIPTION {
            get {
                return ResourceManager.GetString("SRG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching and Replacing.
        /// </summary>
        internal static string SRG_NAME {
            get {
                return ResourceManager.GetString("SRG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has the attribute of System or ReadOnly, which prevents the setting..
        /// </summary>
        internal static string TEXT_ATTRIBUTE_PREVENT_SETTING {
            get {
                return ResourceManager.GetString("TEXT_ATTRIBUTE_PREVENT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because this Gulu operation doesn&apos;t require backup, and the operation cannot be rolled back. Please confirm by entering &quot;OK&quot; below. Otherwise the operation will be canceled..
        /// </summary>
        internal static string TEXT_INPUT_OK_TEXT {
            get {
                return ResourceManager.GetString("TEXT_INPUT_OK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input OK.
        /// </summary>
        internal static string TEXT_INPUT_OK_TITLE {
            get {
                return ResourceManager.GetString("TEXT_INPUT_OK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is invalid..
        /// </summary>
        internal static string TEXT_INVALID_OPERATION {
            get {
                return ResourceManager.GetString("TEXT_INVALID_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} ....
        /// </summary>
        internal static string TEXT_PROCESSING {
            get {
                return ResourceManager.GetString("TEXT_PROCESSING", resourceCulture);
            }
        }
    }
}
