//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunnyChen.Gulu.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SunnyChen.Gulu.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_ASKQUESTION {
            get {
                object obj = ResourceManager.GetObject("BMP_ASKQUESTION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_CALCULATOR {
            get {
                object obj = ResourceManager.GetObject("BMP_CALCULATOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_CONFIGURATION {
            get {
                object obj = ResourceManager.GetObject("BMP_CONFIGURATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_COPY {
            get {
                object obj = ResourceManager.GetObject("BMP_COPY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_CUT {
            get {
                object obj = ResourceManager.GetObject("BMP_CUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_DELETE {
            get {
                object obj = ResourceManager.GetObject("BMP_DELETE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_DELETE2 {
            get {
                object obj = ResourceManager.GetObject("BMP_DELETE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_DYNAMICHELP {
            get {
                object obj = ResourceManager.GetObject("BMP_DYNAMICHELP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_EDITOR {
            get {
                object obj = ResourceManager.GetObject("BMP_EDITOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_ERRORLIST {
            get {
                object obj = ResourceManager.GetObject("BMP_ERRORLIST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_FILELIST {
            get {
                object obj = ResourceManager.GetObject("BMP_FILELIST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_FILTER {
            get {
                object obj = ResourceManager.GetObject("BMP_FILTER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_FIND {
            get {
                object obj = ResourceManager.GetObject("BMP_FIND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_GOTOLINE {
            get {
                object obj = ResourceManager.GetObject("BMP_GOTOLINE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_GScriptManager {
            get {
                object obj = ResourceManager.GetObject("BMP_GScriptManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_GULU {
            get {
                object obj = ResourceManager.GetObject("BMP_GULU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_HOME {
            get {
                object obj = ResourceManager.GetObject("BMP_HOME", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_OPEN {
            get {
                object obj = ResourceManager.GetObject("BMP_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_OUTPUT {
            get {
                object obj = ResourceManager.GetObject("BMP_OUTPUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_PASTE {
            get {
                object obj = ResourceManager.GetObject("BMP_PASTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_PREFERENCES {
            get {
                object obj = ResourceManager.GetObject("BMP_PREFERENCES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_REDO {
            get {
                object obj = ResourceManager.GetObject("BMP_REDO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_RUN {
            get {
                object obj = ResourceManager.GetObject("BMP_RUN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_SCRIPT {
            get {
                object obj = ResourceManager.GetObject("BMP_SCRIPT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_SESSIONSTATUS {
            get {
                object obj = ResourceManager.GetObject("BMP_SESSIONSTATUS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_UNDO {
            get {
                object obj = ResourceManager.GetObject("BMP_UNDO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_UPDATELIST {
            get {
                object obj = ResourceManager.GetObject("BMP_UPDATELIST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BMP_USERGUIDE {
            get {
                object obj = ResourceManager.GetObject("BMP_USERGUIDE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Properties.
        /// </summary>
        internal static string FORMAT_PROPERTY_EDITOR_TITLE {
            get {
                return ResourceManager.GetString("FORMAT_PROPERTY_EDITOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ICO_COMPILE {
            get {
                object obj = ResourceManager.GetObject("ICO_COMPILE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ICO_ERROR {
            get {
                object obj = ResourceManager.GetObject("ICO_ERROR", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ICO_INFO {
            get {
                object obj = ResourceManager.GetObject("ICO_INFO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ICO_WARNING {
            get {
                object obj = ResourceManager.GetObject("ICO_WARNING", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JPG_GULU {
            get {
                object obj = ResourceManager.GetObject("JPG_GULU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JPG_GULU_ABOUT {
            get {
                object obj = ResourceManager.GetObject("JPG_GULU_ABOUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add or Remove Buttons.
        /// </summary>
        internal static string TEXT_ADD_REMOVE_BTNS {
            get {
                return ResourceManager.GetString("TEXT_ADD_REMOVE_BTNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Arrange Icons.
        /// </summary>
        internal static string TEXT_ARRANGE_ICONS {
            get {
                return ResourceManager.GetString("TEXT_ARRANGE_ICONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed on the file {0}..
        /// </summary>
        internal static string TEXT_BACKUP_FAILED {
            get {
                return ResourceManager.GetString("TEXT_BACKUP_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cascade.
        /// </summary>
        internal static string TEXT_CASCADE {
            get {
                return ResourceManager.GetString("TEXT_CASCADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string TEXT_CATEGORY {
            get {
                return ResourceManager.GetString("TEXT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lose All Windows.
        /// </summary>
        internal static string TEXT_CLOSE_ALL_WINDOWS {
            get {
                return ResourceManager.GetString("TEXT_CLOSE_ALL_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Editor - {0}, {1}.
        /// </summary>
        internal static string TEXT_CODEEDITOR_TITLE {
            get {
                return ResourceManager.GetString("TEXT_CODEEDITOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        internal static string TEXT_COL_ERRORCODE {
            get {
                return ResourceManager.GetString("TEXT_COL_ERRORCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string TEXT_COL_ERRORLEVEL {
            get {
                return ResourceManager.GetString("TEXT_COL_ERRORLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number.
        /// </summary>
        internal static string TEXT_COL_ERRORLINE {
            get {
                return ResourceManager.GetString("TEXT_COL_ERRORLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Text.
        /// </summary>
        internal static string TEXT_COL_ERRORTEXT {
            get {
                return ResourceManager.GetString("TEXT_COL_ERRORTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile accomplished successfully..
        /// </summary>
        internal static string TEXT_COMPILE_OK {
            get {
                return ResourceManager.GetString("TEXT_COMPILE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder for backup..
        /// </summary>
        internal static string TEXT_CONFIG_BACKUP_PATH_DESC {
            get {
                return ResourceManager.GetString("TEXT_CONFIG_BACKUP_PATH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will clear all the items in the file list, do you wish to continue?.
        /// </summary>
        internal static string TEXT_CONFIRM_CLEARLIST {
            get {
                return ResourceManager.GetString("TEXT_CONFIRM_CLEARLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected item is going to be deleted, are you sure?.
        /// </summary>
        internal static string TEXT_CONFIRM_DELETE_ITEM {
            get {
                return ResourceManager.GetString("TEXT_CONFIRM_DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is going to interrupt current process, are you sure?.
        /// </summary>
        internal static string TEXT_CONFIRM_INTERRUPT {
            get {
                return ResourceManager.GetString("TEXT_CONFIRM_INTERRUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will interrupt the searching process, continue?.
        /// </summary>
        internal static string TEXT_CONFIRM_INTERRUPT_SEARCHING {
            get {
                return ResourceManager.GetString("TEXT_CONFIRM_INTERRUPT_SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script has been changed, do you want to save changes?.
        /// </summary>
        internal static string TEXT_CONFIRM_SAVE_SCRIPT {
            get {
                return ResourceManager.GetString("TEXT_CONFIRM_SAVE_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string TEXT_CONFIRMATION {
            get {
                return ResourceManager.GetString("TEXT_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Customize....
        /// </summary>
        internal static string TEXT_CUSTOMIZE {
            get {
                return ResourceManager.GetString("TEXT_CUSTOMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT_NAMESPACE.
        /// </summary>
        internal static string TEXT_DEFAULT_NAMESPACE {
            get {
                return ResourceManager.GetString("TEXT_DEFAULT_NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string TEXT_DESKTOP {
            get {
                return ResourceManager.GetString("TEXT_DESKTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer manual doesn&apos;t exist..
        /// </summary>
        internal static string TEXT_DEVELOPERMANUAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("TEXT_DEVELOPERMANUAL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing Gulu... .
        /// </summary>
        internal static string TEXT_DONE_GULU {
            get {
                return ResourceManager.GetString("TEXT_DONE_GULU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile failed..
        /// </summary>
        internal static string TEXT_ERR_COMPILE {
            get {
                return ResourceManager.GetString("TEXT_ERR_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error occurs while compiles..
        /// </summary>
        internal static string TEXT_ERR_COMPILE_GENERAL {
            get {
                return ResourceManager.GetString("TEXT_ERR_COMPILE_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unable to load code structure.).
        /// </summary>
        internal static string TEXT_ERR_GET_CODE_STRUCT {
            get {
                return ResourceManager.GetString("TEXT_ERR_GET_CODE_STRUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code has not been added to compiler..
        /// </summary>
        internal static string TEXT_ERR_NO_CODE {
            get {
                return ResourceManager.GetString("TEXT_ERR_NO_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TEXT_ERROR {
            get {
                return ResourceManager.GetString("TEXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has already been added to the list..
        /// </summary>
        internal static string TEXT_FILE_ALREADY_ADDED {
            get {
                return ResourceManager.GetString("TEXT_FILE_ALREADY_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} doesn&apos;t exist, ignored..
        /// </summary>
        internal static string TEXT_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("TEXT_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] Operation FAILED on file {0}..
        /// </summary>
        internal static string TEXT_FILE_OPER_FAILED {
            get {
                return ResourceManager.GetString("TEXT_FILE_OPER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string TEXT_FILTERS {
            get {
                return ResourceManager.GetString("TEXT_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Places.
        /// </summary>
        internal static string TEXT_GENERAL_ROOT {
            get {
                return ResourceManager.GetString("TEXT_GENERAL_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G scripts.
        /// </summary>
        internal static string TEXT_GSCRIPT_ROOT {
            get {
                return ResourceManager.GetString("TEXT_GSCRIPT_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize the Gulu, operation cancelled..
        /// </summary>
        internal static string TEXT_GULU_INIT_FAILED {
            get {
                return ResourceManager.GetString("TEXT_GULU_INIT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gulus.
        /// </summary>
        internal static string TEXT_GULUS {
            get {
                return ResourceManager.GetString("TEXT_GULUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list is not open yet.
        ///Please open the file list from main menu, drop some file into the file list and be sure the files are selected..
        /// </summary>
        internal static string TEXT_INFO_FILELIST_NOT_OPEN {
            get {
                return ResourceManager.GetString("TEXT_INFO_FILELIST_NOT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected tree node is not a valid file tree node..
        /// </summary>
        internal static string TEXT_INFO_INVALID_NODE {
            get {
                return ResourceManager.GetString("TEXT_INFO_INVALID_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of current tree node is not supported..
        /// </summary>
        internal static string TEXT_INFO_NODETYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TEXT_INFO_NODETYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is selected in the file list or the file list is empty.
        ///Please drop some file into the file list and be sure they are selected..
        /// </summary>
        internal static string TEXT_INFO_NOITEM {
            get {
                return ResourceManager.GetString("TEXT_INFO_NOITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TEXT_INFORMATION {
            get {
                return ResourceManager.GetString("TEXT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing CodeDom Compiler....
        /// </summary>
        internal static string TEXT_INIT_COMPILER {
            get {
                return ResourceManager.GetString("TEXT_INIT_COMPILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing components....
        /// </summary>
        internal static string TEXT_INIT_COMPONENTS {
            get {
                return ResourceManager.GetString("TEXT_INIT_COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing control states....
        /// </summary>
        internal static string TEXT_INIT_CONTROLSTATES {
            get {
                return ResourceManager.GetString("TEXT_INIT_CONTROLSTATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Gulu... currently {0}.
        /// </summary>
        internal static string TEXT_INIT_GULU {
            get {
                return ResourceManager.GetString("TEXT_INIT_GULU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Gulu manager....
        /// </summary>
        internal static string TEXT_INIT_GULUMANAGER {
            get {
                return ResourceManager.GetString("TEXT_INIT_GULUMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting event handlers....
        /// </summary>
        internal static string TEXT_INIT_SETEVENTHANDLERS {
            get {
                return ResourceManager.GetString("TEXT_INIT_SETEVENTHANDLERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting session parameters....
        /// </summary>
        internal static string TEXT_INIT_SETSESSIONPARAM {
            get {
                return ResourceManager.GetString("TEXT_INIT_SETSESSIONPARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing file tree view....
        /// </summary>
        internal static string TEXT_INIT_TREEVIEW {
            get {
                return ResourceManager.GetString("TEXT_INIT_TREEVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating elements....
        /// </summary>
        internal static string TEXT_INIT_UPDATEELEMENTS {
            get {
                return ResourceManager.GetString("TEXT_INIT_UPDATEELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the name of the script that you want to create. This name string should begin with underscores or letters, then followed by underscores, letters or digits. Creating the script with the existing names will be rejected..
        /// </summary>
        internal static string TEXT_INPUTNAME {
            get {
                return ResourceManager.GetString("TEXT_INPUTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input name.
        /// </summary>
        internal static string TEXT_INPUTNAME_TITLE {
            get {
                return ResourceManager.GetString("TEXT_INPUTNAME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize All Windows.
        /// </summary>
        internal static string TEXT_MIN_ALL_WINDOWS {
            get {
                return ResourceManager.GetString("TEXT_MIN_ALL_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        internal static string TEXT_MYDOCUMENT {
            get {
                return ResourceManager.GetString("TEXT_MYDOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TEXT_NAME {
            get {
                return ResourceManager.GetString("TEXT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na&amp;vigation Pane Options....
        /// </summary>
        internal static string TEXT_NAV_PANE_OPTIONS {
            get {
                return ResourceManager.GetString("TEXT_NAV_PANE_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FONT SIZE=&quot;2.5px&quot; FACE=&quot;Tahoma&quot; COLOR=&quot;GRAY&quot;&gt;Currently no documentation is available for the selected item.&lt;/FONT&gt;.
        /// </summary>
        internal static string TEXT_NO_DOCUMENT_AVAILABLE {
            get {
                return ResourceManager.GetString("TEXT_NO_DOCUMENT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setting options for the current item.
        /// </summary>
        internal static string TEXT_NO_SETTINGS {
            get {
                return ResourceManager.GetString("TEXT_NO_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not specified).
        /// </summary>
        internal static string TEXT_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("TEXT_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} was not found..
        /// </summary>
        internal static string TEXT_PATH_NOT_FOUND {
            get {
                return ResourceManager.GetString("TEXT_PATH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRE-RELEASE.
        /// </summary>
        internal static string TEXT_PRERELEASE {
            get {
                return ResourceManager.GetString("TEXT_PRERELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler type: {0}.
        /// </summary>
        internal static string TEXT_PROMPT_COMPILER_TYPE {
            get {
                return ResourceManager.GetString("TEXT_PROMPT_COMPILER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded gulus: {0}.
        /// </summary>
        internal static string TEXT_PROMPT_LOADED_GULUS {
            get {
                return ResourceManager.GetString("TEXT_PROMPT_LOADED_GULUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session name: {0}.
        /// </summary>
        internal static string TEXT_PROMPT_SESSION_NAME {
            get {
                return ResourceManager.GetString("TEXT_PROMPT_SESSION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed: {0}.
        /// </summary>
        internal static string TEXT_PROMPT_TIME_ELAPSED {
            get {
                return ResourceManager.GetString("TEXT_PROMPT_TIME_ELAPSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string TEXT_PROPERTY {
            get {
                return ResourceManager.GetString("TEXT_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string TEXT_READY {
            get {
                return ResourceManager.GetString("TEXT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given script name already exists..
        /// </summary>
        internal static string TEXT_SCRIPT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("TEXT_SCRIPT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates and syntax file must be specified for each type of script..
        /// </summary>
        internal static string TEXT_SCRIPT_MUST_SPECIFY {
            get {
                return ResourceManager.GetString("TEXT_SCRIPT_MUST_SPECIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search completed..
        /// </summary>
        internal static string TEXT_SEARCH_COMPLETED {
            get {
                return ResourceManager.GetString("TEXT_SEARCH_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files found..
        /// </summary>
        internal static string TEXT_SEARCH_RESULT {
            get {
                return ResourceManager.GetString("TEXT_SEARCH_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching directories, {0} items found....
        /// </summary>
        internal static string TEXT_SEARCHING_DIRECTORY {
            get {
                return ResourceManager.GetString("TEXT_SEARCHING_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the type for the compiler. The type must be derived from SunnyChen.Common.CodeDom.Compiler..
        /// </summary>
        internal static string TEXT_SELCOMPILER_DESC {
            get {
                return ResourceManager.GetString("TEXT_SELCOMPILER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select compiler type.
        /// </summary>
        internal static string TEXT_SELCOMPILER_TITLE {
            get {
                return ResourceManager.GetString("TEXT_SELCOMPILER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Fewer Buttons.
        /// </summary>
        internal static string TEXT_SHOW_FEWER_BTNS {
            get {
                return ResourceManager.GetString("TEXT_SHOW_FEWER_BTNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;More Buttons.
        /// </summary>
        internal static string TEXT_SHOW_MORE_BTNS {
            get {
                return ResourceManager.GetString("TEXT_SHOW_MORE_BTNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple scripts.
        /// </summary>
        internal static string TEXT_SIMPLESCRIPT_ROOT {
            get {
                return ResourceManager.GetString("TEXT_SIMPLESCRIPT_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Places.
        /// </summary>
        internal static string TEXT_SPECIAL_ROOT {
            get {
                return ResourceManager.GetString("TEXT_SPECIAL_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gulu is terminated normally..
        /// </summary>
        internal static string TEXT_TERMINATED_NORMALLY {
            get {
                return ResourceManager.GetString("TEXT_TERMINATED_NORMALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gulu is interrupted by user..
        /// </summary>
        internal static string TEXT_TERMINATED_USER {
            get {
                return ResourceManager.GetString("TEXT_TERMINATED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Hori&amp;zontally.
        /// </summary>
        internal static string TEXT_TILE_HORI {
            get {
                return ResourceManager.GetString("TEXT_TILE_HORI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile &amp;Vertically.
        /// </summary>
        internal static string TEXT_TILE_VERT {
            get {
                return ResourceManager.GetString("TEXT_TILE_VERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User guide doesn&apos;t exist..
        /// </summary>
        internal static string TEXT_USERGUIDE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TEXT_USERGUIDE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gulu already exists. Program will continue but it will discard the duplicated gulus. Whether the gulu is duplicated depends on the Identifier property.
        ///
        ///Gulu information:
        ///
        ///{0}.
        /// </summary>
        internal static string TEXT_WARN_GULU_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("TEXT_WARN_GULU_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TEXT_WARNING {
            get {
                return ResourceManager.GetString("TEXT_WARNING", resourceCulture);
            }
        }
    }
}
